// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DeleteConfirmController from "./delete_confirm_controller";
application.register("delete-confirm", DeleteConfirmController);

import QuantityVisibilityController from "./quantity_visibility_controller";
application.register("quantity-visibility", QuantityVisibilityController);
