// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import MobileMenusController from "./mobile_menus_controller"
application.register("mobile-menus", MobileMenusController)

import ModalFrameController from "./modal_frame_controller"
application.register("modal-frame", ModalFrameController)

import PushController from "./push_controller"
application.register("push", PushController)

import QuantityVisibilityController from "./quantity_visibility_controller"
application.register("quantity-visibility", QuantityVisibilityController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TempleteSelectController from "./templete_select_controller"
application.register("templete-select", TempleteSelectController)
