privacy:
  - comment: "<!-- 1. 収集する情報 -->"
    title: "第1条 （収集する情報）"
    body: |
      <p class="mb-2">本サービスでは、以下の情報を収集する場合があります。</p>
      <div class="space-y-4">
        <div>
          <h3 class="font-medium mb-1">（1）Googleログインを通じて取得する情報</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>メールアドレス</li>
            <li>ユーザー名（Googleアカウントに登録されている名前）</li>
          </ul>
          <p class="mb-2">これらの情報は、ユーザー認証およびアカウント管理の目的でのみ利用します。</p>
        </div>
        <div>
          <h3 class="font-medium mb-1">（2）Google Analyticsによるアクセス解析情報</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>閲覧ページ、利用時間、ブラウザ・OS情報、アクセス元地域などの統計情報</li>
          </ul>
          <p class="mb-2">これらの情報は匿名で収集され、個人を特定するものではありません。</p>
        </div>
        <div>
          <h3 class="font-medium mb-1">（3）プッシュ通知に関する端末情報</h3>
          <p class="mb-2">
            本サービスではパートナー間の通知機能にプッシュ通知を採用しています。
            プッシュ通知の送信にあたり、通知配信に必要な以下の情報を取得します。
          </p>
          <ul class="list-disc pl-6 space-y-1">
            <li>通知を配信する端末識別情報（Push通知用エンドポイントURL、暗号鍵など）</li>
          </ul>
          <p class="mb-2">
            これらの情報は、ログイン済みのユーザーに限定して取得され、通知の送信にのみ利用されます。
            個人を特定する目的では利用しません。
          </p>
        </div>
      </div>

  - comment: "<!-- 2. 情報の利用目的 -->"
    title: "第2条 （情報の利用目的）"
    body: |
      <ul class="list-disc pl-6 space-y-1">
        <li>本サービスへのログインおよびユーザー認証のため</li>
        <li>利用状況の分析および機能改善のため</li>
      </ul>

  - comment: "<!-- 3. 情報の第三者提供 -->"
    title: "第3条 （情報の第三者提供）"
    body: |
      <p class="mb-2">本サービスは、以下の場合を除き、ユーザーの個人情報を第三者に提供することはありません。</p>
      <ul class="list-disc pl-6 space-y-1">
        <li>ユーザー本人の同意がある場合</li>
        <li>法令に基づき開示が必要とされる場合</li>
      </ul>

  - comment: "<!-- 4. 情報の管理 -->"
    title: "第4条 （情報の管理）"
    body: |
      <p>
        本サービスは、収集した情報を適切に管理し、不正アクセス、紛失、改ざん、漏えいなどの防止に努めます。
        本サービスのデータは、本サービスが利用するクラウドサービスのサーバー上に安全に保存されます。
      </p>

  - comment: "<!-- 5. 外部サービスの利用について -->"
    title: "第5条 （外部サービスの利用について）"
    body: |
      <p class="mb-2">本サービスでは以下の外部サービスを利用しています。各サービスのプライバシーポリシーをご確認ください。</p>
      <ul class="list-disc pl-6 space-y-1">
        <li>
          <a href="https://policies.google.com/privacy" class="underline hover:no-underline" target="_blank" rel="noopener noreferrer">
            Google ログイン（OAuth）
          </a>
        </li>
        <li>
          <a href="https://marketingplatform.google.com/about/analytics/terms/jp/" class="underline hover:no-underline" target="_blank" rel="noopener noreferrer">
            Google Analytics
          </a>
        </li>
      </ul>

  - comment: "<!-- 6. ユーザーの権利 -->"
    title: "第6条 （ユーザーの権利）"
    body: |
      <p class="mb-2">
        ユーザーは、ご自身のGoogleアカウント設定から、連携情報の確認・削除を行うことができます。
        また、今後お問い合わせフォームを設け、個別の削除依頼にも対応できるよう検討しています。
      </p>

  - comment: "<!-- 7. プライバシーポリシーの変更 -->"
    title: "第7条 （プライバシーポリシーの変更）"
    body: |
      <p>
        本サービスは、法令改正やサービス内容の変更に応じて、本プライバシーポリシーを改定することがあります。
        変更後のプライバシーポリシーは、本サービス上に掲示した時点から効力を生じるものとします。
      </p>

  - comment: "<!-- 8. お問い合わせ -->"
    title: "第8条 （お問い合わせ）"
    body: |
      <p>
        プライバシーに関するお問い合わせは、問い合わせフォームよりご連絡ください。
      </p>
