terms:
  - comment: "<!-- 1. 適用 -->"
    title: "第1条 （適用）"
    body: |
      <p>
        本規約は、本サービスの利用に関する一切の関係に適用されるものとします。
      </p>

  - comment: "<!-- 2. 利用登録 -->"
    title: "第2条 （利用登録）"
    body: |
      <p class="mb-2">
        本サービスは、Googleアカウントによるログイン認証をもって登録を完了とします。
        登録時に取得する情報は、メールアドレスおよびユーザー名に限られます。
      </p>
      <p>
        登録情報に虚偽、誤記、または不正があった場合、当社は当該ユーザーの利用を停止または登録を削除することがあります。
      </p>

  - comment: "<!-- 3. 禁止事項 -->"
    title: "第3条 （禁止事項）"
    body: |
      <p class="mb-2">ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。</p>
      <ul class="list-disc pl-6 space-y-1">
        <li>法令または公序良俗に違反する行為</li>
        <li>他のユーザーまたは第三者の権利を侵害する行為</li>
        <li>本サービスの運営を妨害する行為</li>
        <li>不正な目的で本サービスを利用する行為</li>
        <li>本サービス管理者が不適切と判断する行為</li>
      </ul>

  - comment: "<!-- 4. サービスの提供停止 -->"
    title: "第4条 （サービスの提供停止）"
    body: |
      <p>
        本サービスは、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部を停止・中断することができます。
      </p>
      <ul class="list-disc pl-6 space-y-1 mt-2">
        <li>システムの保守点検または更新を行う場合</li>
        <li>火災、停電、地震などの不可抗力により提供が困難になった場合</li>
        <li>その他、本サービスの運営を継続できないと判断した場合</li>
      </ul>
      <p class="mt-2">
        本サービスは、これによりユーザーに生じた損害について一切の責任を負いません。
      </p>

  - comment: "<!-- 5. 免責事項 -->"
    title: "第5条 （免責事項）"
    body: |
      <p class="mb-2">
        本サービスは、ユーザーが本サービスを利用したこと、または利用できなかったことによって生じた損害について、一切の責任を負いません。
      </p>
      <p>
        本サービスの内容は、ユーザーの利便性向上を目的として提供されるものであり、正確性や完全性を保証するものではありません。
      </p>

  - comment: "<!-- 6. 利用制限・登録抹消 -->"
    title: "第6条 （利用制限・登録抹消）"
    body: |
      <p>
        ユーザーが本規約に違反した場合、または不正利用が確認された場合、本サービスは事前の通知なくアカウントを停止または削除することができます。
      </p>

  - comment: "<!-- 7. サービス内容の変更・終了 -->"
    title: "第7条 （サービス内容の変更・終了）"
    body: |
      <p>
        本サービスは、ユーザーへの事前通知をもって、内容の変更、追加、または終了を行うことがあります。
        サービス終了により生じた損害について、本サービスは一切の責任を負いません。
      </p>

  - comment: "<!-- 8. 規約の変更 -->"
    title: "第8条 （規約の変更）"
    body: |
      <p>
        本サービスは、必要と判断した場合、ユーザーへの通知をもって本規約を変更することができます。
        変更後にユーザーが本サービスを利用した場合、変更後の規約に同意したものとみなします。
      </p>

  - comment: "<!-- 9. 準拠法・管轄 -->"
    title: "第9条 （準拠法・管轄）"
    body: |
      <p>
        本規約の解釈には日本法を準拠法とし、本サービスに関して紛争が生じた場合は、日本国内の裁判所を専属的合意管轄とします。
      </p>
